const inputs = [
  {
    id: 1,
    name: "firstName",
    type: "text",
    placeholder: "First Name",
    errorMessage: "Enter a valid first name",
    label: "First Name",
    required: true,
    materialUIcomponent: "TextField",
  },
  {
    id: 2,
    name: "lastName",
    type: "text",
    placeholder: "Last Name",
    errorMessage: "Enter a valid last name",
    label: "Last Name",
    required: true,
    materialUIcomponent: "TextField",
  },
  {
    id: 3,
    name: "serviceBegin",
    type: "date",
    placeholder: "Service Begin",
    errorMessage: "Enter a valid service begin date.",
    label: "Service Begin",
    required: true,
    materialUIcomponent: "TextField",
  },
  {
    id: 4,
    name: "firstName",
    type: "text",
    placeholder: "First Name",
    errorMessage: "Enter a valid first name",
    label: "First Name",
    required: true,
    materialUIcomponent: "TextField",
  },
  {
    id: 5,
    name: "payor",
    type: "",
    placeholder: "Payor",
    errorMessage: "Enter a payor",
    label: "Payor",
    required: true,
    materialUIcomponent: "Select",
    options: ["Humana", "UHC", "Cetna"],
  },
];

export default inputs;
